### ISSUE TITLE
Docet Maven plugin sometimes is really slow due to IndexWriter#forceMerge

### ISSUE THREAD

**Issue by eolivelli** [diennea/docetproject#23]
On my jenkins the build is really slow, this is the stacktrace.

Maybe there could be an option to compact the index ?

```
"pool-1-thread-1 for channel id=48208" Id=12 Group=main RUNNABLE (in native)
	at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
	at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
	at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:55)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:70)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:48)
	at sun.nio.fs.LinuxFileSystem.getFileStore(LinuxFileSystem.java:112)
	at sun.nio.fs.UnixFileSystem$FileStoreIterator.readNext(UnixFileSystem.java:213)
	at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
	-  locked sun.nio.fs.UnixFileSystem$FileStoreIterator@103d9f84
	at org.apache.lucene.util.IOUtils.getFileStore(IOUtils.java:515)
	at org.apache.lucene.util.IOUtils.spinsLinux(IOUtils.java:459)
	at org.apache.lucene.util.IOUtils.spins(IOUtils.java:448)
	at org.apache.lucene.util.IOUtils.spins(IOUtils.java:423)
	at org.apache.lucene.index.ConcurrentMergeScheduler.initDynamicDefaults(ConcurrentMergeScheduler.java:376)
	-  locked org.apache.lucene.index.ConcurrentMergeScheduler@2646ee62
	at org.apache.lucene.index.ConcurrentMergeScheduler.merge(ConcurrentMergeScheduler.java:464)
	-  locked org.apache.lucene.index.ConcurrentMergeScheduler@2646ee62
	at org.apache.lucene.index.IndexWriter.maybeMerge(IndexWriter.java:1931)
	at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3088)
	at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1741)
	at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1721)
	at docet.maven.DocetPluginUtils.indexDocsForLanguage(DocetPluginUtils.java:1285)
	at docet.maven.DocetPluginUtils.indexDocs(DocetPluginUtils.java:1225)
	at docet.maven.DocetMojo.execute(DocetMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
```

**Comment by caiok** [comment]
On my laptop the build is stuck in the same place
```
	at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
	- locked <0x00000007708b7f70> (a sun.nio.fs.UnixFileSystem$FileStoreIterator)
	at org.apache.lucene.util.IOUtils.getFileStore(IOUtils.java:515)
	at org.apache.lucene.util.IOUtils.spinsLinux(IOUtils.java:459)
	at org.apache.lucene.util.IOUtils.spins(IOUtils.java:448)
	at org.apache.lucene.util.IOUtils.spins(IOUtils.java:423)
	at org.apache.lucene.index.ConcurrentMergeScheduler.initDynamicDefaults(ConcurrentMergeScheduler.java:376)
	- locked <0x000000077d167f00> (a org.apache.lucene.index.ConcurrentMergeScheduler)
	at org.apache.lucene.index.ConcurrentMergeScheduler.merge(ConcurrentMergeScheduler.java:464)
	- locked <0x000000077d167f00> (a org.apache.lucene.index.ConcurrentMergeScheduler)
	at org.apache.lucene.index.IndexWriter.maybeMerge(IndexWriter.java:1931)
	at org.apache.lucene.index.IndexWriter.flush(IndexWriter.java:3088)
	at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1741)
	at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1721)
	at docet.maven.DocetPluginUtils.indexDocsForLanguage(DocetPluginUtils.java:1285)
	at docet.maven.DocetPluginUtils.indexDocs(DocetPluginUtils.java:1225)
	at docet.maven.DocetMojo.execute(DocetMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

```
