### ISSUE TITLE
Docet >illegalArgumentException while search a script: example (<script type="text/vbscript">alert(kappa)</script>)

### ISSUE THREAD

**Issue by hamadodene** [diennea/docetproject#49]
18-10-04-12-25-00       java.lang.IllegalArgumentException: expected '>' at position 26
java.lang.IllegalArgumentException: expected '>' at position 26
        at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1127)
        at org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:1090)
        at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1078)
        at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1047)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1040)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1041)
        at org.apache.lucene.util.automaton.RegExp.parseInterExp(RegExp.java:1033)
        at org.apache.lucene.util.automaton.RegExp.parseUnionExp(RegExp.java:1027)
        at org.apache.lucene.util.automaton.RegExp.<init>(RegExp.java:405)
        at org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:108)
        at org.apache.lucene.search.RegexpQuery.<init>(RegexpQuery.java:93)
        at org.apache.lucene.queryparser.classic.QueryParserBase.newRegexpQuery(QueryParserBase.java:580)
        at org.apache.lucene.queryparser.classic.QueryParserBase.getRegexpQuery(QueryParserBase.java:781)
        at org.apache.lucene.queryparser.classic.QueryParserBase.handleBareTokenQuery(QueryParserBase.java:851)
        at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:348)
        at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:247)
        at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:202)
        at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:160)
        at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:117)
        at docet.engine.SimpleDocetDocSearcher.searchForMatchingDocuments(SimpleDocetDocSearcher.java:104)
        at docet.engine.DocetManager.searchPagesByKeywordAndLangWithRerencePackage(DocetManager.java:796)
        at docet.engine.DocetManager.serveSearchRequest(DocetManager.java:1129)
        at docet.engine.DocetManager.serveRequest(DocetManager.java:1023)
        at docet.engine.DocetManager.serveRequest(DocetManager.java:907)
        at magnews.gateway.docet.DocetSimpleServlet.processRequest(DocetSimpleServlet.java:69)
        at magnews.gateway.docet.DocetSimpleServlet.doGet(DocetSimpleServlet.java:53)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
:

**Comment by eolivelli** [comment]
Thank you for reporting this.
We are going to create a new release soon. We can work on a fix.
Or maybe you can try to fix and sned a PR

**Comment by eolivelli** [comment]
@diegosalvi  did you solve this one ?
